[package]
name = "noodles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

noodles = {version = "0.33.0", features = ["bam",  "sam", "bgzf", "core"]}
anyhow = "1.0"
rayon = "1.7"
